server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          username: ''
          password: ''
          searchPaths: respo
          #uri: https://github.com/forezp/SpringcloudConfig
          uri: file:///D:/my-project/temp/localgit
